version: '3'
services:
  
  mongodb:
    image: mongo 
    ports:
      - "27017:27017"
    volumes:
      - mymongo-data:/data/db


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: db_1122
      POSTGRES_DB: database
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  web:
    depends_on: 
      - mongodb
      - postgres
      - redis
    links:
      - mongodb:mongodb
      - postgres:postgres
      - redis:redis  
    build: .
    restart: always
    ports:
      - "80:80"
      
  

volumes:
  mysql_data:
  postgres_data:
  mymongo-data:
